version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: echo "Sorry... It don't support. User `docker-compose run --rm app bash`"
    volumes:
      - .:/app
    env_file:
      - .env
    links:
      - dynamodb-local

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - 8801:8800
    environment:
      DEFAULT_REGION: ap-northeast-1
