Resources:
  apiC8550315:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: api
    Metadata:
      aws:cdk:path: api/api/Resource
  apiCloudWatchRoleAC81D93E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: api/api/CloudWatchRole/Resource
  apiAccount57E28B43:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - apiCloudWatchRoleAC81D93E
          - Arn
    DependsOn:
      - apiC8550315
    Metadata:
      aws:cdk:path: api/api/Account
  apiDeployment149F1294afedaf16f5a192a0af0a2fe837e8a0ea:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: apiC8550315
      Description: Automatically created by the RestApi construct
    DependsOn:
      - apiGETECF0BD67
      - apiuserproxyANY5BB97033
      - apiuserproxy1E92B772
      - apiuserANY0FA3232B
      - apiuserE5DA65CB
    Metadata:
      aws:cdk:path: api/api/Deployment/Resource
  apiDeploymentStageprod896C8101:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: apiC8550315
      DeploymentId:
        Ref: apiDeployment149F1294afedaf16f5a192a0af0a2fe837e8a0ea
      StageName: prod
    Metadata:
      aws:cdk:path: api/api/DeploymentStage.prod/Resource
  apiGETECF0BD67:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Fn::GetAtt:
          - apiC8550315
          - RootResourceId
      RestApiId:
        Ref: apiC8550315
      AuthorizationType: NONE
      Integration:
        Type: MOCK
    Metadata:
      aws:cdk:path: api/api/Default/GET/Resource
  apiuserE5DA65CB:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - apiC8550315
          - RootResourceId
      PathPart: user
      RestApiId:
        Ref: apiC8550315
    Metadata:
      aws:cdk:path: api/api/Default/user/Resource
  apiuserANYApiPermissionapi4F59AA66ANYuser0E0217ED:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - UserFunction89BB1343
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiC8550315
            - /
            - Ref: apiDeploymentStageprod896C8101
            - /*/user
    Metadata:
      aws:cdk:path: api/api/Default/user/ANY/ApiPermission.api4F59AA66.ANY..user
  apiuserANYApiPermissionTestapi4F59AA66ANYuserF7268895:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - UserFunction89BB1343
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiC8550315
            - /test-invoke-stage/*/user
    Metadata:
      aws:cdk:path: api/api/Default/user/ANY/ApiPermission.Test.api4F59AA66.ANY..user
  apiuserANY0FA3232B:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: apiuserE5DA65CB
      RestApiId:
        Ref: apiC8550315
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - UserFunction89BB1343
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: api/api/Default/user/ANY/Resource
  apiuserproxy1E92B772:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Ref: apiuserE5DA65CB
      PathPart: "{proxy+}"
      RestApiId:
        Ref: apiC8550315
    Metadata:
      aws:cdk:path: api/api/Default/user/{proxy+}/Resource
  apiuserproxyANYApiPermissionapi4F59AA66ANYuserproxy00369F2E:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - UserFunction89BB1343
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiC8550315
            - /
            - Ref: apiDeploymentStageprod896C8101
            - /*/user/*
    Metadata:
      aws:cdk:path: api/api/Default/user/{proxy+}/ANY/ApiPermission.api4F59AA66.ANY..user.{proxy+}
  apiuserproxyANYApiPermissionTestapi4F59AA66ANYuserproxy53EAEFBD:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - UserFunction89BB1343
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiC8550315
            - /test-invoke-stage/*/user/*
    Metadata:
      aws:cdk:path: api/api/Default/user/{proxy+}/ANY/ApiPermission.Test.api4F59AA66.ANY..user.{proxy+}
  apiuserproxyANY5BB97033:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: apiuserproxy1E92B772
      RestApiId:
        Ref: apiC8550315
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - UserFunction89BB1343
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: api/api/Default/user/{proxy+}/ANY/Resource
  IssuesRoleC20FB3B7:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AWSXRayDaemonWriteAccess
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
    Metadata:
      aws:cdk:path: api/IssuesRole/Resource
  IssuesRoleDefaultPolicy793FF711:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: dynamodb:*
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: IssuesRoleDefaultPolicy793FF711
      Roles:
        - Ref: IssuesRoleC20FB3B7
    Metadata:
      aws:cdk:path: api/IssuesRole/DefaultPolicy/Resource
  UserFunction89BB1343:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters533319143e47908bafc15d35fee538c9ca55f5f645aa0741d1d48904b1aed911S3BucketED9E0067
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters533319143e47908bafc15d35fee538c9ca55f5f645aa0741d1d48904b1aed911S3VersionKeyAA1C772D
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters533319143e47908bafc15d35fee538c9ca55f5f645aa0741d1d48904b1aed911S3VersionKeyAA1C772D
      Handler: main
      Role:
        Fn::GetAtt:
          - IssuesRoleC20FB3B7
          - Arn
      Runtime: go1.x
      FunctionName: UserFunction
    DependsOn:
      - IssuesRoleDefaultPolicy793FF711
      - IssuesRoleC20FB3B7
    Metadata:
      aws:cdk:path: api/UserFunction/Resource
      aws:asset:path: /Users/jumpyoshim/jumpyoshim/gin-lambda/funcs/user
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.74.0,@aws-cdk/assets=1.74.0,@aws-cdk/aws-apigateway=1.74.0,@aws-cdk/aws-applicationautoscaling=1.74.0,@aws-cdk/aws-autoscaling-common=1.74.0,@aws-cdk/aws-cloudwatch=1.74.0,@aws-cdk/aws-codeguruprofiler=1.74.0,@aws-cdk/aws-ec2=1.74.0,@aws-cdk/aws-events=1.74.0,@aws-cdk/aws-iam=1.74.0,@aws-cdk/aws-kms=1.74.0,@aws-cdk/aws-lambda=1.74.0,@aws-cdk/aws-logs=1.74.0,@aws-cdk/aws-s3=1.74.0,@aws-cdk/aws-s3-assets=1.74.0,@aws-cdk/aws-sqs=1.74.0,@aws-cdk/aws-ssm=1.74.0,@aws-cdk/cloud-assembly-schema=1.74.0,@aws-cdk/core=1.74.0,@aws-cdk/cx-api=1.74.0,@aws-cdk/region-info=1.74.0,jsii-runtime=node.js/v14.5.0
    Metadata:
      aws:cdk:path: api/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  apiEndpoint9349E63C:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: apiC8550315
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: apiDeploymentStageprod896C8101
          - /
Parameters:
  AssetParameters533319143e47908bafc15d35fee538c9ca55f5f645aa0741d1d48904b1aed911S3BucketED9E0067:
    Type: String
    Description: S3 bucket for asset "533319143e47908bafc15d35fee538c9ca55f5f645aa0741d1d48904b1aed911"
  AssetParameters533319143e47908bafc15d35fee538c9ca55f5f645aa0741d1d48904b1aed911S3VersionKeyAA1C772D:
    Type: String
    Description: S3 key for asset version "533319143e47908bafc15d35fee538c9ca55f5f645aa0741d1d48904b1aed911"
  AssetParameters533319143e47908bafc15d35fee538c9ca55f5f645aa0741d1d48904b1aed911ArtifactHashDAC7B3FD:
    Type: String
    Description: Artifact hash for asset "533319143e47908bafc15d35fee538c9ca55f5f645aa0741d1d48904b1aed911"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

